### ISSUE TITLE
Left click closes tabs in Arc Browser

### ISSUE THREAD

**Issue by Sklpcc** [croian/mouseless#147]
### mouseless version

0.2.2

### macOS version

15.2

### Other system input apps

Hyperkey

### What happened?

Using `space` on a tab in Arc's sidebar, closes the tab instead of open it.

It happens in the stable and pre-release versions (0.3.0-preview.3).

https://github.com/user-attachments/assets/4f264c07-1fbe-4f9f-bdb1-d1c16a78669f

### Steps to Reproduce

- Show overlay
- Select column and row targeting a tab
- Press `space`

**Comment by ognistik** [comment]
I use Arc and can't reproduce (I actually use Mouseless a lot to switch tabs this way). My guess is that it has to do with something in your config.

**Comment by Sklpcc** [comment]
These are my settings.
I didn't touch any chromium settings directly, only Arc ones.

<details><summary>Screenshots</summary>
<p>

<img width="614" alt="Image" src="https://github.com/user-attachments/assets/0d73c567-77e6-481d-936f-8643c01c51f9" />

<img width="599" alt="Image" src="https://github.com/user-attachments/assets/9615b3e6-4947-4bb9-83a9-67ab073e31da" />

<img width="590" alt="Image" src="https://github.com/user-attachments/assets/032a6296-21eb-4162-a5e4-8024f77d8002" />

<img width="586" alt="Image" src="https://github.com/user-attachments/assets/f5063c12-9f98-4203-866b-37ec5d0c97d8" />

<img width="601" alt="Image" src="https://github.com/user-attachments/assets/81b4e57b-c72b-43a0-9902-8ce0477e5b54" />

<img width="594" alt="Image" src="https://github.com/user-attachments/assets/4a1334cf-362c-4998-b0bd-8e9d5aafc552" />

</p>
</details> 

I can reproduce it in incognito without any extension enabled.
Also, I forgot to mention that it doesn't always happen.

<details><summary>Videos</summary>
<p>

https://github.com/user-attachments/assets/420e796c-14f7-47d6-928d-d107b94f04b7

(Sorry for the bad quality, but GitHub rejects the original file)

https://github.com/user-attachments/assets/dd531eaa-c04c-43db-b9dc-510ef6020d95

</p>
</details>

**Comment by Sklpcc** [comment]
>do you notice any difference in behavior between when arc has focus and when it doesn't?

Do you mean if there is a difference when the browser has focus vs when the web page has focus before the click? If that is the case, no, it happens in both cases. Arc is the only app where I have noticed any strange behavior (although I only use left click for now).

<details><summary>Mousless Config</summary>
<p>

```yaml
app_version: 0.3.0-preview.3
behavior_configs:
- base_wheel_speed: 16
  hide_cursor_on_click: false
  hide_location: bottom_left
  move_duration_ms: 100
  move_real_cursor_with_virtual: false
  multi_action_timeout_ms: 400
  name: main_behavior
  tap_threshold_ms: 200
  wheel_mode_auto_off_s: 10
  wheel_speed_multiplier: 4
  wheel_step_size: 100
  wheel_step_size_large: 500
classname: AppConfig
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 26
    num_cells_y: 1
  - border_width: 1
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 26
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
  mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
  name: full_alpha
  strategy: subgrid
  subgrid_dims:
  - 8
  - 3
  subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    num_cells_x: 1
    num_cells_y: 26
  - border_width: 1.0
    callback: build_cell_strings
    num_cells_x: 26
    num_cells_y: 1
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    num_cells_x: 2
    num_cells_y: 1
  mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
  name: vertical_alpha
  strategy: subgrid
  subgrid_dims:
  - 4
  - 6
  subgrid_mouse_action_keys: QWERASDFZXCVUIOPJKL;M,./
keymaps:
- entries:
    close dialog: OptionRight
    cycle click count: null
    cycle mouse action type: null
    cycle mouse button: null
    edit config: Tab
    execute mouse action: Space
    hide overlay: Escape
    hold for drag: CommandLeft
    hold for move: OptionLeft
    hold for right button: CommandRight
    release hold/drag: OptionRight
    repeat last mouse action: null
    show overlay: CommandLeft tap
    switch monitor left: ShiftLeft tap
    switch monitor right: ShiftRight tap
    toggle overlay: null
  name: mac
monitor_assignments: auto
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.3
  background_rgba:
  - 0
  - 0
  - 0
  - 0.1
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  cursor_drag_rgba:
  - 1.0
  - 0.5
  - 0.0
  - 0.7
  cursor_move_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 0.0
  - 1.0
  - 0.3
  - 0.7
  cursor_right_button_rgba:
  - 1.0
  - 0.3
  - 0.3
  - 0.7
  cursor_size: 7
  font_size_multiplier: 0.5
  grid_line_style: lines
  grid_rgba:
  - 0.996078431372549
  - 0.996078431372549
  - 0.996078431372549
  - 0.5
  highlight_rgba:
  - 0.996078431372549
  - 0.996078431372549
  - 0.996078431372549
  - 0.3
  name: dark_bg
  subgrid_font_size_multiplier: 0.75
  subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.9
  subgrid_text_rgba:
  - 1
  - 1
  - 1
  - 0.9
  text_rgba:
  - 1
  - 1
  - 1
  - 1
  text_shadow_blur_radius: 2
  text_shadow_offset:
  - 1.0
  - -1.0
  text_shadow_rgba:
  - 0
  - 0
  - 0
  - 1
  window_opacity: 0.6
```

</p>
</details>
