### ISSUE TITLE
🚨 Mac 0.4.0-preview.2 feedback and questions thread

### ISSUE THREAD

**Issue by croian** [croian/mouseless#277]
Thread for the latest [Windows beta release](https://github.com/croian/mouseless-issues/releases/tag/v0.4.0-preview.2)

Feel free to discuss here or create new bug reports!

Thank you, and enjoy! 🚀

**Comment by croian** [comment]
Thank you for the report, @ilyagr -- will look into this right away.  When you say the overlay stopped working, do you mean `show overlay` stopped working?  Or you weren't able to select cells?  Or something else?

**Comment by ilyagr** [comment]
"show overlay" stopped working.

**Comment by ilyagr** [comment]
I thin the presets not working is a separate problem. I tried reproducing my old config and this config, made purely with mouseless 0.4 beta, has `show overlay` not working either.

<details><summary> Full config </summary>

```yaml
app_version: 0.4.0-preview.2
behavior_configs:
- base_move_speed: 5.0
  base_wheel_speed: 16.0
  free_mode_auto_off_s: 10
  grid_action_level: subgrid
  hide_cursor_on_click: false
  hide_location: bottom_left
  initial_action_location: system_cursor
  initial_overlay_monitor: last_used
  move_duration_ms: 100
  move_real_cursor_with_virtual: false
  move_speed_multiplier: 3.0
  movement_easing: 0.1
  multi_action_timeout_ms: 400
  name: main_behavior
  send_escape_after_global_alt_tap__windows: true
  tap_threshold_ms: 300
  wheel_easing: 0.1
  wheel_speed_multiplier: 4.0
  wheel_step_size: 100.0
  wheel_step_size_large: 500.0
classname: AppConfig
custom_monitor_assignments: []
display_input: none
event_tap_location: hid_head
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[],./\`
    num_cells_x: 45
    num_cells_y: 1
  - border_width: 1.0
    callback: build_cell_strings
    keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[],./\`
    num_cells_x: 1
    num_cells_y: 33
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: true
  name: column_row_45x33_4x4
  nudges_per_cell: 4
  strategy: subgrid
  subgrid_dims:
  - 4
  - 4
  subgrid_mouse_action_keys: WERT SDFG YUIO HJKL
keyboard_layout:
  id: com.apple.keylayout.UnicodeHexInput
  name: Unicode Hex Input
  vk_to_char:
    0:
    - a
    - A
    1:
    - s
    - S
    2:
    - d
    - D
    3:
    - f
    - F
    4:
    - h
    - H
    5:
    - g
    - G
    6:
    - z
    - Z
    7:
    - x
    - X
    8:
    - c
    - C
    9:
    - v
    - V
    10:
    - "\xA7"
    - "\xB1"
    11:
    - b
    - B
    12:
    - q
    - Q
    13:
    - w
    - W
    14:
    - e
    - E
    15:
    - r
    - R
    16:
    - y
    - Y
    17:
    - t
    - T
    18:
    - '1'
    - '!'
    19:
    - '2'
    - '@'
    20:
    - '3'
    - '#'
    21:
    - '4'
    - $
    22:
    - '6'
    - ^
    23:
    - '5'
    - '%'
    24:
    - '='
    - +
    25:
    - '9'
    - (
    26:
    - '7'
    - '&'
    27:
    - '-'
    - _
    28:
    - '8'
    - '*'
    29:
    - '0'
    - )
    30:
    - ']'
    - '}'
    31:
    - o
    - O
    32:
    - u
    - U
    33:
    - '['
    - '{'
    34:
    - i
    - I
    35:
    - p
    - P
    36: "\r"
    37:
    - l
    - L
    38:
    - j
    - J
    39:
    - ''''
    - '"'
    40:
    - k
    - K
    41:
    - ;
    - ':'
    42:
    - \
    - '|'
    43:
    - ','
    - <
    44:
    - /
    - '?'
    45:
    - n
    - N
    46:
    - m
    - M
    47:
    - .
    - '>'
    48: "\t"
    49: ' '
    50:
    - '`'
    - '~'
    51: "\b"
    52: "\x03"
    53: "\e"
    65: .
    66:
    - "\x1D"
    - '*'
    67: '*'
    68: "\0"
    69: +
    70:
    - "\x1C"
    - +
    71: "\e"
    72:
    - "\x1F"
    - '='
    73: "\0"
    74: "\0"
    75: /
    76: "\x03"
    77:
    - "\x1E"
    - /
    78: '-'
    79: "\0"
    80: "\0"
    81: '='
    82: '0'
    83: '1'
    84: '2'
    85: '3'
    86: '4'
    87: '5'
    88: '6'
    89: '7'
    90: "\0"
    91: '8'
    92: '9'
    93: "\0"
    94: "\0"
    95: "\0"
    96: "\x10"
    97: "\x10"
    98: "\x10"
    99: "\x10"
    100: "\x10"
    101: "\x10"
    102: "\x10"
    103: "\x10"
    104: "\x10"
    105: "\x10"
    106: "\x10"
    107: "\x10"
    108: "\x10"
    109: "\x10"
    110: "\x10"
    111: "\x10"
    112: "\x10"
    113: "\x10"
    114: "\x05"
    115: "\x01"
    116: "\v"
    117: "\x7F"
    118: "\x10"
    119: "\x04"
    120: "\x10"
    121: "\f"
    122: "\x10"
    123: "\x1C"
    124: "\x1D"
    125: "\x1F"
    126: "\x1E"
    127: "\0"
keymaps:
- entries:
    back mouse button: null
    back mouse button (w/o overlay): null
    close UI element: Escape
    cycle click count: null
    cycle font: null
    cycle font reverse: null
    cycle grid action level: null
    cycle mouse action type: null
    cycle mouse button: null
    decrease overlay opacity: ArrowDown
    edit config: Tab
    enter free mode: null
    execute mouse action: Space
    execute mouse move: OptionLeft tap
    exit free mode: Escape
    forward mouse button: null
    forward mouse button (w/o overlay): null
    hide overlay: Escape
    hold for back button: null
    hold for drag: CommandLeft
    hold for forward button: null
    hold for middle button: null
    hold for move: OptionLeft
    hold for right button: CommandRight
    hold for speed decrease: null
    hold for speed increase:
    - A
    - S
    - D
    - F
    increase overlay opacity: ArrowUp
    jump to bottom: null
    jump to left edge: null
    jump to right edge: null
    jump to top: null
    left mouse button: null
    left mouse button (w/o overlay): null
    middle mouse button: null
    middle mouse button (w/o overlay): null
    move down: null
    move left: null
    move right: null
    move up: null
    release hold/drag: Escape
    repeat last mouse action: Enter
    right mouse button: null
    right mouse button (w/o overlay): null
    show overlay: Option + Command tap
    subgrid nudge down:
    - D
    - K
    subgrid nudge left:
    - S
    - J
    subgrid nudge right:
    - F
    - L
    subgrid nudge up:
    - E
    - I
    switch monitor left: ShiftLeft tap
    switch monitor right: ShiftRight tap
    toggle continuous mode: null
    toggle continuous mode until closed: null
    toggle free mode: Command + Option tap
    toggle overlay: null
    toggle overlay lock: null
    undo last key: Backspace
    wheel down: J
    wheel down fast: null
    wheel left: H
    wheel left fast: null
    wheel right: L
    wheel right fast: null
    wheel step down: null
    wheel step down large: null
    wheel step left: null
    wheel step left large: null
    wheel step right: null
    wheel step right large: null
    wheel step up: null
    wheel step up large: null
    wheel up: K
    wheel up fast: null
  name: mac
monitor_assignment_mode: auto
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.2
  background_rgba:
  - 0.49
  - 0.4
  - 0.0
  - 0.35
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  cursor_drag_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_move_rgba:
  - 0.75
  - 0.41
  - 0.92
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 0.3
  - 0.42
  - 0.58
  - 0.8
  cursor_right_button_rgba:
  - 0.92
  - 0.32
  - 0.32
  - 0.7
  cursor_size: 7
  font_family: MS Sans Serif
  font_size_multiplier: 0.4
  font_weight: 500
  grid_line_style: lines
  grid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  highlight_animation_ms: 0
  highlight_rgba:
  - 0.21
  - 0.48
  - 0.95
  - 0.2
  name: default
  show_initial_highlight: false
  subgrid_font_size_multiplier: 0.75
  subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  subgrid_text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  text_shadow_blur_radius: 2.0
  text_shadow_offset:
  - 1.0
  - -1.0
  text_shadow_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  text_y_offset: 0.0
  window_opacity: 0.9
```

</details>

All I changed since it was last working was the grid config. I think that trying this preset (with the Unicode Hex Input input method) might be sufficient to demo the bug:

```yaml
app_version: 0.4.0-preview.2
classname: PresetColl
name: ''
preset_data:
  grid_configs:
    column_row_45x33_4x4:
    - always_show_subgrid: false
      grid_defn:
      - border_width: 0
        callback: build_cell_strings
        keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[],./\`
        num_cells_x: 45
        num_cells_y: 1
      - border_width: 1
        callback: build_cell_strings
        keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[],./\`
        num_cells_x: 1
        num_cells_y: 33
      - border_width: 0
        callback: apply_strings_and_subgrid_to_cells
        keys: ''
        num_cells_x: 2
        num_cells_y: 1
      hold_subgrid_key_for_nudge: true
      name: column_row_45x33_4x4
      nudges_per_cell: 4
      strategy: subgrid
      subgrid_dims:
      - 4
      - 4
      subgrid_mouse_action_keys: WERT SDFG YUIO HJKL
```

**Comment by ilyagr** [comment]
Removing ```,./\` ``` from the end of the `keys` and changing the `num_cells_x` to 40 makes the overlay work again.

**Comment by ilyagr** [comment]
I'm having a new, separate problem with preview2. Using below config (quite similar to the previous one, I think I only changed the shadow), the overlay works, but it doesn't register any keys I press *in* the overlay. (So, e.g. if I press `AA` to try to click in the top-left, nothing happens).

I tried the setting to "show input", and Mouseless does see the `A` key being pressed, but the click doesn't happen for some reason.

<details>

```yaml
app_version: 0.4.0-preview.2
behavior_configs:
- base_move_speed: 5.0
  base_wheel_speed: 16.0
  free_mode_auto_off_s: 10
  grid_action_level: subgrid
  hide_cursor_on_click: false
  hide_location: bottom_left
  initial_action_location: system_cursor
  initial_overlay_monitor: last_used
  move_duration_ms: 100
  move_real_cursor_with_virtual: false
  move_speed_multiplier: 3.0
  movement_easing: 0.1
  multi_action_timeout_ms: 400
  name: main_behavior
  send_escape_after_global_alt_tap__windows: true
  tap_threshold_ms: 300
  wheel_easing: 0.1
  wheel_speed_multiplier: 4.0
  wheel_step_size: 100.0
  wheel_step_size_large: 500.0
classname: AppConfig
custom_monitor_assignments: []
display_input: none
event_tap_location: hid_head
grid_configs:
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[]
    num_cells_x: 40
    num_cells_y: 1
  - border_width: 1.0
    callback: build_cell_strings
    keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[]
    num_cells_x: 1
    num_cells_y: 33
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: false
  name: column_row_45x33_4x4
  nudges_per_cell: 4
  strategy: subgrid
  subgrid_dims:
  - 4
  - 4
  subgrid_mouse_action_keys: WERT SDFG YUIO HJKL
- always_show_subgrid: false
  grid_defn:
  - border_width: 0.0
    callback: build_cell_strings
    keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[]
    num_cells_x: 33
    num_cells_y: 1
  - border_width: 1.0
    callback: build_cell_strings
    keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-=[]
    num_cells_x: 1
    num_cells_y: 40
  - border_width: 0.0
    callback: apply_strings_and_subgrid_to_cells
    keys: ''
    num_cells_x: 2
    num_cells_y: 1
  hold_subgrid_key_for_nudge: false
  name: column_row_33x45_4x4
  nudges_per_cell: 4
  strategy: subgrid
  subgrid_dims:
  - 4
  - 4
  subgrid_mouse_action_keys: WERT SDFG YUIO HJKL
keyboard_layout:
  id: com.apple.keylayout.UnicodeHexInput
  name: Unicode Hex Input
  vk_to_char:
    0:
    - a
    - A
    1:
    - s
    - S
    2:
    - d
    - D
    3:
    - f
    - F
    4:
    - h
    - H
    5:
    - g
    - G
    6:
    - z
    - Z
    7:
    - x
    - X
    8:
    - c
    - C
    9:
    - v
    - V
    10:
    - "\xA7"
    - "\xB1"
    11:
    - b
    - B
    12:
    - q
    - Q
    13:
    - w
    - W
    14:
    - e
    - E
    15:
    - r
    - R
    16:
    - y
    - Y
    17:
    - t
    - T
    18:
    - '1'
    - '!'
    19:
    - '2'
    - '@'
    20:
    - '3'
    - '#'
    21:
    - '4'
    - $
    22:
    - '6'
    - ^
    23:
    - '5'
    - '%'
    24:
    - '='
    - +
    25:
    - '9'
    - (
    26:
    - '7'
    - '&'
    27:
    - '-'
    - _
    28:
    - '8'
    - '*'
    29:
    - '0'
    - )
    30:
    - ']'
    - '}'
    31:
    - o
    - O
    32:
    - u
    - U
    33:
    - '['
    - '{'
    34:
    - i
    - I
    35:
    - p
    - P
    36: "\r"
    37:
    - l
    - L
    38:
    - j
    - J
    39:
    - ''''
    - '"'
    40:
    - k
    - K
    41:
    - ;
    - ':'
    42:
    - \
    - '|'
    43:
    - ','
    - <
    44:
    - /
    - '?'
    45:
    - n
    - N
    46:
    - m
    - M
    47:
    - .
    - '>'
    48: "\t"
    49: ' '
    50:
    - '`'
    - '~'
    51: "\b"
    52: "\x03"
    53: "\e"
    65: .
    66:
    - "\x1D"
    - '*'
    67: '*'
    68: "\0"
    69: +
    70:
    - "\x1C"
    - +
    71: "\e"
    72:
    - "\x1F"
    - '='
    73: "\0"
    74: "\0"
    75: /
    76: "\x03"
    77:
    - "\x1E"
    - /
    78: '-'
    79: "\0"
    80: "\0"
    81: '='
    82: '0'
    83: '1'
    84: '2'
    85: '3'
    86: '4'
    87: '5'
    88: '6'
    89: '7'
    90: "\0"
    91: '8'
    92: '9'
    93: "\0"
    94: "\0"
    95: "\0"
    96: "\x10"
    97: "\x10"
    98: "\x10"
    99: "\x10"
    100: "\x10"
    101: "\x10"
    102: "\x10"
    103: "\x10"
    104: "\x10"
    105: "\x10"
    106: "\x10"
    107: "\x10"
    108: "\x10"
    109: "\x10"
    110: "\x10"
    111: "\x10"
    112: "\x10"
    113: "\x10"
    114: "\x05"
    115: "\x01"
    116: "\v"
    117: "\x7F"
    118: "\x10"
    119: "\x04"
    120: "\x10"
    121: "\f"
    122: "\x10"
    123: "\x1C"
    124: "\x1D"
    125: "\x1F"
    126: "\x1E"
    127: "\0"
keymaps:
- entries:
    back mouse button: null
    back mouse button (w/o overlay): null
    close UI element: Escape
    cycle click count: null
    cycle font: null
    cycle font reverse: null
    cycle grid action level: null
    cycle mouse action type: null
    cycle mouse button: null
    decrease overlay opacity: ArrowDown
    edit config: Tab
    enter free mode: null
    execute mouse action: Space
    execute mouse move: OptionLeft tap
    exit free mode: Escape
    forward mouse button: null
    forward mouse button (w/o overlay): null
    hide overlay: Escape
    hold for back button: null
    hold for drag: CommandLeft
    hold for forward button: null
    hold for middle button: null
    hold for move: OptionLeft
    hold for right button: CommandRight
    hold for speed decrease: null
    hold for speed increase:
    - A
    - S
    - D
    - F
    increase overlay opacity: ArrowUp
    jump to bottom: null
    jump to left edge: null
    jump to right edge: null
    jump to top: null
    left mouse button: null
    left mouse button (w/o overlay): null
    middle mouse button: null
    middle mouse button (w/o overlay): null
    move down: null
    move left: null
    move right: null
    move up: null
    release hold/drag: Escape
    repeat last mouse action: Enter
    right mouse button: null
    right mouse button (w/o overlay): null
    show overlay: Option + Command tap
    subgrid nudge down:
    - D
    - K
    subgrid nudge left:
    - S
    - J
    subgrid nudge right:
    - F
    - L
    subgrid nudge up:
    - E
    - I
    switch monitor left: ShiftLeft tap
    switch monitor right: ShiftRight tap
    toggle continuous mode: null
    toggle continuous mode until closed: null
    toggle free mode: Command + Option tap
    toggle overlay: null
    toggle overlay lock: null
    undo last key: Backspace
    wheel down: J
    wheel down fast: null
    wheel left: H
    wheel left fast: null
    wheel right: L
    wheel right fast: null
    wheel step down: null
    wheel step down large: null
    wheel step left: null
    wheel step left large: null
    wheel step right: null
    wheel step right large: null
    wheel step up: null
    wheel step up large: null
    wheel up: K
    wheel up fast: null
  name: mac
monitor_assignment_mode: auto
name: ''
style_configs:
- always_on_subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.2
  background_rgba:
  - 0.49
  - 0.4
  - 0.0
  - 0.35
  char_spacing_cell_width_ratio: 0.5
  char_spacing_font_size_ratio: 0.5
  char_spacing_strategy: cell_width_relative
  cursor_drag_rgba:
  - 0.0
  - 0.5
  - 1.0
  - 0.7
  cursor_move_rgba:
  - 0.75
  - 0.41
  - 0.92
  - 0.7
  cursor_other_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.7
  cursor_rgba:
  - 0.3
  - 0.42
  - 0.58
  - 0.8
  cursor_right_button_rgba:
  - 0.92
  - 0.32
  - 0.32
  - 0.7
  cursor_size: 7
  font_family: MS Sans Serif
  font_size_multiplier: 0.4
  font_weight: 500
  grid_line_style: lines
  grid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  highlight_animation_ms: 0
  highlight_rgba:
  - 0.21
  - 0.48
  - 0.95
  - 0.2
  name: default
  show_initial_highlight: false
  subgrid_font_size_multiplier: 0.75
  subgrid_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  subgrid_text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 0.5
  text_rgba:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  text_shadow_blur_radius: 1
  text_shadow_offset:
  - 1.0
  - 1
  text_shadow_rgba:
  - 0
  - 0
  - 0
  - 1
  text_y_offset: 0.0
  window_opacity: 0.9
```

</details>
